GET http://localhost:8080/projects

###

GET http://localhost:3001/projects/64ed02b1753f3e32ac652cf0

###

POST http://localhost:8080/projects
Content-Type: application/json

{
    "title": "Personal Website",
    "description": "You're on it right now!",
    "tech_stack": "React.js, Express.js (Node.js), MongoDB, AWS S3/Elastic Beanstalk",
    "code_url": "https://github.com/JoshLiCoding/Personal-Website-Frontend",
    "website_url": "https://joshuali.ca/",
    "photo_url": "https://jl-personal-website-bucket.s3.ca-central-1.amazonaws.com/personalthumbnail.png"
}

###

DELETE http://localhost:3001/projects/64efb6f97c47205722797154

###
PATCH http://localhost:3001/projects/64efa32ee09fbf33568a5e2b
Content-Type: application/json

{
    "website_url": ""
}